### ISSUE TITLE
Cluster overview shows wrong guest usernames

### ISSUE THREAD

**Issue by lemairecarl** [ComputeCanada/mc-hub#31]
The cluster overview UI shows `user1` instead of `user01`.

**Comment by lefreud** [comment]
Thanks for pointing out this bug. From what I understand, you created a cluster with 2 users and MC Hub showed the user range (user1 - user2).

Magic Castle does indeed seem to be creating user01 and user02 instead. However, according to the documentation (https://github.com/ComputeCanada/magic_castle/tree/master/docs#410-nb_users), it should be creating user1 and user2 (because nb_users is lower than 10). What do you think @cmd-ntrf ?

**Comment by cmd-ntrf** [comment]
It's a bug in Magic Castle. The way we zero-pad the username, there is always at least one zero.

I will fix this in puppet-magic_castle.

**Comment by cmd-ntrf** [comment]
Fixed by https://github.com/ComputeCanada/puppet-magic_castle/pull/100

It will be part of Magic Castle 10.
